### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by exetico** [Goeny/slicker#1]
Do you have any examples, of how it looks? Will it be compitable with the latest version of SickRage?

Best Regards

**Comment by Goeny** [comment]
I stopped this project because the sickrage dev-team switched to Mako while i was still working with cheetah.

It shouldn't be to hard to make the conversion in the theme aswell but i simply don't have the time right now.

That being said:
- The current Slicker theme files are NOT compatible with the current Sickrage version
- The screenshots can be found here [https://www.sickrage.ca/forums/forum/help-support/general-support/22882-new-theme-fanart]

**Comment by exetico** [comment]
Thanks for taking you time to answer anyways :-)
